server:
  port: ${PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      bindings:
        output:
          destination: test
          contentType: application/json
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ac
        uri: lb://aircraft-service
        predicates:
        - Path=/ac/**
        filters:
        - RewritePath=/ac/, /
      - id: aircraft
        uri: lb://aircraft-service
        predicates:
        - Path=/aircraft
        filters:
        - name: Resilience4j
          args:
            name: fallbackcmd
            fallbackUri: forward:/favorite
        - RewritePath=/aircraft, /aircraft/favorite

  zipkin:
    host: localhost
    port: 9411
    base-url: http://localhost:9411
    sender:
      type: web

# Misc
aircraft: "PA28"
