server:
  port: ${PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    port: 6379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      bindings:
        output:
          destination: test
          contentType: application/json
          
  zipkin:
    host: localhost
    port: 9411
    base-url: http://localhost:9411
    sender:
      type: web

# Misc
aircraft: "PA28"
