server:
  port: ${PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    aircraft-service:
      path: /ac/**
    demo:
      path: /aircraft/**
      url: forward:/upintheair
    # wx:
    #   path: /weather/**
    #   url: forward:http://api.openweathermap.org/data/2.5/find

spring:
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      bindings:
        output:
          destination: test
          contentType: application/json
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cs
        uri: lb://aircraft-service
        predicates:
        - Path=/ac/**
        filters:
        - RewritePath=/ac/, /
      - id: coffee
        uri: lb://aircraft-service
        predicates:
        - Path=/aircraft
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/favorite
        - RewritePath=/aircraft, /aircraft/random

  zipkin:
    host: localhost
    port: 9411
    base-url: http://localhost:9411
    sender:
      type: web

# Misc
aircraft: "PA28"
