server:
  port: ${PORT:8080}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: report
          uri: lb://report-service
          predicates:
            - Path=/report/**
          filters:
            - RewritePath=/report, /

#       - id: ac
#         uri: lb://aircraft-service/
#         predicates:
#         - Path=/ac/**
#       - id: aircraft
#         uri: lb://aircraft-service/
#         predicates:
#         - Path=/aircraft/**
