server:
  port: ${PORT:8080}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: edge
          uri: lb://edge-service
          predicates:
            - Path=/edge/**
          filters:
            - RewritePath=/edge, /

# spring:
#   cloud:
#     gateway:
#       routes:
#       - id: edge
#         uri: lb://edge-service/
#         predicates:
#         - Path=/edge/**
#       - id: ac
#         uri: lb://aircraft-service/
#         predicates:
#         - Path=/ac/**
#       - id: aircraft
#         uri: lb://aircraft-service/
#         predicates:
#         - Path=/aircraft/**
