server:
  port: ${PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  zipkin:
    host: localhost
    port: 9411
    base-url: http://localhost:9411
    sender:
      type: web

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Misc
aircraft: "PA28"
